apiVersion: v1
kind: Namespace
metadata:
  name: model-garden
  labels:
    app.kubernetes.io/part-of: model-garden
    pod-security.kubernetes.io/audit: restricted
    pod-security.kubernetes.io/warn: restricted
