apiVersion: v1
kind: Service
metadata:
  name: model-garden-gateway
  namespace: model-garden
  labels:
    app.kubernetes.io/name: model-garden-gateway
    app.kubernetes.io/part-of: model-garden
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: model-garden-gateway
  ports:
    - name: http
      port: 4000
      targetPort: http
